<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 20px 24px; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #1A1A1A; margin: 0; }
        .band { background: #C41230; color: #fff; padding: 10px 16px; font-weight: bold; font-size: 13px; }
        .band .sub { font-weight: normal; font-size: 9px; }
        h1 { font-size: 16px; margin: 16px 0 4px; }
        .subtitle { color: #6B7280; font-size: 9px; margin-bottom: 10px; }
        table.meta { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
        table.meta td { padding: 2px 8px 2px 0; font-size: 9px; }
        table.meta td.label { color: #8A8F98; font-weight: bold; width: 110px; }
        h2 { font-size: 12px; margin: 18px 0 6px; border-bottom: 2px solid #C41230; padding-bottom: 4px; }
        .kpis { width: 100%; margin-bottom: 10px; }
        .kpi { display: inline-block; border: 1px solid #E4E5E8; padding: 6px 10px; margin: 0 6px 6px 0; }
        .kpi b { display: block; font-size: 13px; }
        table.data { width: 100%; border-collapse: collapse; font-size: 8.5px; margin-bottom: 12px; }
        table.data th { background: #C41230; color: #fff; text-align: left; padding: 5px; }
        table.data td { border: 1px solid #E4E5E8; padding: 5px; }
        table.data tr:nth-child(even) td { background: #FAFAFB; }
        .footer { color: #8A8F98; font-size: 8px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="band">
        SEBENARNYA.MY &middot; OFFICIAL REPORT
        <div class="sub">{{ $org ?? 'Malaysian Communications and Multimedia Commission (MCMC)' }}</div>
    </div>

    <h1>{{ $title }}</h1>
    @if (! empty($subtitle))
        <div class="subtitle">{{ $subtitle }}</div>
    @endif

    <table class="meta">
        <tr>
            <td class="label">REPORT ID</td><td>{{ $reportId }}</td>
            <td class="label">GENERATED BY</td><td>{{ $generatedBy }}</td>
        </tr>
        <tr>
            <td class="label">PERIOD</td><td>{{ $period }}</td>
            <td class="label">GENERATED ON</td><td>{{ $generatedOn }}</td>
        </tr>
    </table>

    @foreach ($sections as $section)
        <h2>{{ $section['name'] }}</h2>

        @if (! empty($section['kpis']))
            <div class="kpis">
                @foreach ($section['kpis'] as $kpi)
                    <div class="kpi">{{ $kpi['label'] }}<b>{{ $kpi['value'] }}</b></div>
                @endforeach
            </div>
        @endif

        @foreach ($section['tables'] as $table)
            @if (! empty($table['heading']))
                <div style="font-weight:bold; font-size: 10px; margin-bottom: 4px;">{{ $table['heading'] }}</div>
            @endif
            <table class="data">
                <thead>
                    <tr>
                        @foreach ($table['columns'] as $column)
                            <th>{{ $column }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @forelse ($table['rows'] as $row)
                        <tr>
                            @foreach ($row as $cell)
                                <td>{{ $cell }}</td>
                            @endforeach
                        </tr>
                    @empty
                        <tr><td colspan="{{ count($table['columns']) }}" style="text-align:center; color:#8A8F98; font-style: italic;">No records match the selected filters.</td></tr>
                    @endforelse
                </tbody>
            </table>
        @endforeach
    @endforeach

    <div class="footer">
        SEBENARNYA.MY &middot; {{ $reportId }} &middot; Generated {{ $generatedOn }} by {{ $generatedBy }}<br>
        CONFIDENTIAL — For official use only. Do not distribute outside authorised agencies.
    </div>
</body>
</html>
