/* SEBENARNYA.MY report exporter — PDF (jsPDF + AutoTable), Excel (SheetJS .xlsx, SpreadsheetML fallback), CSV.
   Spec shape:
   { title, subtitle, filename, org, generatedBy, period, filters: [[label, value]],
     groups: [{ name, kpis: [{label, value, tone}], blocks: [
       { type:'chart', heading, unit, data:[{label, value}] },
       { type:'table', heading, sheet, columns:[...], rows:[[...]], note } ] }] }
*/
(function () {
  var LIBS = {
    jspdf: 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js',
    autotable: 'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js',
    xlsx: 'https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js'
  };
  var loading = {};
  function load(src) {
    if (loading[src]) return loading[src];
    loading[src] = new Promise(function (res, rej) {
      var s = document.createElement('script');
      s.src = src; s.async = true;
      var t = setTimeout(function () { rej(new Error('timeout')); }, 9000);
      s.onload = function () { clearTimeout(t); res(); };
      s.onerror = function () { clearTimeout(t); delete loading[src]; rej(new Error('load failed: ' + src)); };
      document.head.appendChild(s);
    });
    return loading[src];
  }

  var RED = [196, 18, 48], INK = [26, 26, 26], GRAY = [138, 143, 152], LINE = [228, 229, 232];
  var TONES = { red: [196, 18, 48], green: [29, 122, 62], blue: [29, 95, 191], amber: [196, 103, 10], ink: INK };

  function pad(n) { return n < 10 ? '0' + n : '' + n; }
  function stamp(d) {
    var M = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return d.getDate() + ' ' + M[d.getMonth()] + ' ' + d.getFullYear() + ', ' + pad(d.getHours()) + ':' + pad(d.getMinutes());
  }
  function reportId(d) {
    return 'RPT-' + d.getFullYear() + pad(d.getMonth() + 1) + pad(d.getDate()) + '-' + Math.random().toString(36).slice(2, 6).toUpperCase();
  }
  function download(blob, name) {
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url; a.download = name; a.style.display = 'none';
    document.body.appendChild(a); a.click();
    setTimeout(function () { URL.revokeObjectURL(url); a.remove(); }, 1500);
  }
  function fmtSize(b) { return b > 1048576 ? (b / 1048576).toFixed(1) + ' MB' : Math.max(1, Math.round(b / 1024)) + ' KB'; }
  function tables(spec) {
    var out = [];
    spec.groups.forEach(function (g) { g.blocks.forEach(function (b) { if (b.type === 'table') out.push({ group: g.name, block: b }); }); });
    return out;
  }
  function meta(spec) {
    var rows = [['Report ID', spec.id], ['Organisation', spec.org], ['Reporting period', spec.period], ['Generated by', spec.generatedBy], ['Generated on', spec.generatedOn]];
    (spec.filters || []).forEach(function (f) { rows.push(f); });
    return rows;
  }

  /* ---------- PDF ---------- */
  var LOGO_SVG = '<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><defs><clipPath id="c"><circle cx="256" cy="248" r="150"/></clipPath></defs>' +
    '<rect x="16" y="16" width="480" height="480" rx="92" ry="92" fill="#ffffff" stroke="#EDEEF0" stroke-width="4"/>' +
    '<g clip-path="url(#c)"><path d="M 256 248 L 256 98 A 150 150 0 0 1 386 323 Z" fill="#0072bc" opacity="0.3"/><path d="M 256 248 L 386 323 A 150 150 0 0 1 126 323 Z" fill="#e31c79" opacity="0.3"/><path d="M 256 248 L 126 323 A 150 150 0 0 1 256 98 Z" fill="#f5a623" opacity="0.3"/></g>' +
    '<circle cx="256" cy="248" r="192" fill="none" stroke="#C41230" stroke-width="24" stroke-dasharray="34 22" stroke-linecap="round"/>' +
    '<circle cx="256" cy="248" r="165" fill="none" stroke="#C41230" stroke-width="24" stroke-dasharray="30 19" stroke-linecap="round"/>' +
    '<path d="M 168 248 L 224 304 L 344 178" fill="none" stroke="#ffffff" stroke-width="70" stroke-linecap="round" stroke-linejoin="round"/>' +
    '<path d="M 168 248 L 224 304 L 344 178" fill="none" stroke="#C41230" stroke-width="52" stroke-linecap="round" stroke-linejoin="round"/></svg>';
  var logoPng = null;
  function loadLogo() {
    if (logoPng) return Promise.resolve(logoPng);
    return new Promise(function (res) {
      var img = new Image();
      img.onload = function () {
        try { var c = document.createElement('canvas'); c.width = c.height = 512; c.getContext('2d').drawImage(img, 0, 0, 512, 512); logoPng = c.toDataURL('image/png'); } catch (e) { logoPng = null; }
        res(logoPng);
      };
      img.onerror = function () { res(null); };
      img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(LOGO_SVG);
    });
  }
  function drawSeal(doc, x, y, size) {
    size = size || 14;
    if (logoPng) { doc.addImage(logoPng, 'PNG', x, y, size, size); return; }
    doc.setFillColor(255, 255, 255); doc.roundedRect(x, y, 14, 14, 2.6, 2.6, 'F');
    doc.setDrawColor(RED[0], RED[1], RED[2]); doc.setLineWidth(0.9);
    doc.setLineDashPattern([1.1, 0.7], 0); doc.circle(x + 7, y + 7, 5.4, 'S');
    doc.setLineDashPattern([], 0); doc.setLineWidth(1.5); doc.setLineCap('round'); doc.setLineJoin('round');
    doc.lines([[1.8, 1.8], [3.8, -4]], x + 4.3, y + 7.1, [1, 1], 'S', false);
  }
  function drawHeader(doc, full) {
    var h = full ? 24 : 14;
    doc.setFillColor(RED[0], RED[1], RED[2]); doc.rect(0, 0, 210, h, 'F');
    if (full) drawSeal(doc, 12, 5, 14); else drawSeal(doc, 12, 3, 8);
    var x = full ? 30 : 23, y = full ? 14.2 : 9.2;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(full ? 14 : 10);
    [['SE', INK], ['BENAR', [255, 255, 255]], ['NYA.MY', INK]].forEach(function (p) {
      doc.setTextColor(p[1][0], p[1][1], p[1][2]); doc.text(p[0], x, y); x += doc.getTextWidth(p[0]);
    });
    doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5);
    doc.text(full ? 'OFFICIAL REPORT  ·  MALAYSIAN COMMUNICATIONS AND MULTIMEDIA COMMISSION' : 'OFFICIAL REPORT', 198, y, { align: 'right' });
  }
  function toPdf(spec) {
    var jsPDF = window.jspdf && window.jspdf.jsPDF;
    var doc = new jsPDF({ unit: 'mm', format: 'a4' });
    var L = 12, R = 198, W = R - L, BOTTOM = 278, y;
    function ensure(h) { if (y + h > BOTTOM) { doc.addPage(); drawHeader(doc, false); y = 24; } }

    drawHeader(doc, true);
    y = 36;
    doc.setTextColor(INK[0], INK[1], INK[2]); doc.setFont('helvetica', 'bold'); doc.setFontSize(18);
    doc.text(spec.title, L, y); y += 6;
    if (spec.subtitle) { doc.setFont('helvetica', 'normal'); doc.setFontSize(9.5); doc.setTextColor(GRAY[0], GRAY[1], GRAY[2]); doc.text(doc.splitTextToSize(spec.subtitle, W), L, y); y += 7; }

    var m = meta(spec);
    doc.setFillColor(247, 247, 248); doc.setDrawColor(LINE[0], LINE[1], LINE[2]); doc.setLineWidth(0.2);
    var mh = 6 + Math.ceil(m.length / 2) * 6.2;
    doc.roundedRect(L, y, W, mh, 2, 2, 'FD');
    m.forEach(function (row, i) {
      var cx = L + 5 + (i % 2) * (W / 2), cy = y + 7 + Math.floor(i / 2) * 6.2;
      doc.setFont('helvetica', 'bold'); doc.setFontSize(7); doc.setTextColor(GRAY[0], GRAY[1], GRAY[2]);
      doc.text(String(row[0]).toUpperCase(), cx, cy);
      doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(INK[0], INK[1], INK[2]);
      doc.text(doc.splitTextToSize(String(row[1]), W / 2 - 42)[0], cx + 34, cy);
    });
    y += mh + 8;

    spec.groups.forEach(function (g, gi) {
      if (gi > 0) { doc.addPage(); drawHeader(doc, false); y = 26; }
      doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(RED[0], RED[1], RED[2]);
      doc.text('SECTION ' + (gi + 1) + ' OF ' + spec.groups.length, L, y); y += 5.5;
      doc.setFontSize(14); doc.setTextColor(INK[0], INK[1], INK[2]); doc.text(g.name, L, y); y += 2.5;
      doc.setDrawColor(RED[0], RED[1], RED[2]); doc.setLineWidth(0.6); doc.line(L, y, L + 18, y); y += 7;

      if (g.kpis && g.kpis.length) {
        var n = g.kpis.length, gap = 4, bw = (W - gap * (n - 1)) / n;
        ensure(22);
        g.kpis.forEach(function (k, i) {
          var bx = L + i * (bw + gap), c = TONES[k.tone] || INK;
          doc.setFillColor(250, 250, 251); doc.setDrawColor(LINE[0], LINE[1], LINE[2]); doc.setLineWidth(0.2);
          doc.roundedRect(bx, y, bw, 19, 2, 2, 'FD');
          doc.setFillColor(c[0], c[1], c[2]); doc.rect(bx, y + 3, 0.9, 13, 'F');
          doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.setTextColor(GRAY[0], GRAY[1], GRAY[2]);
          doc.text(doc.splitTextToSize(k.label, bw - 7)[0], bx + 4, y + 6.5);
          doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(c[0], c[1], c[2]);
          doc.text(String(k.value), bx + 4, y + 14.5);
        });
        y += 26;
      }

      g.blocks.forEach(function (b) {
        if (b.type === 'chart') {
          if (!b.data.length) return;
          ensure(62);
          doc.setFont('helvetica', 'bold'); doc.setFontSize(10.5); doc.setTextColor(INK[0], INK[1], INK[2]);
          doc.text(b.heading, L, y); y += 5;
          var ch = 42, top = y + 4, base = top + ch, max = Math.max.apply(null, b.data.map(function (d) { return d.value; })) || 1;
          doc.setDrawColor(240, 241, 243); doc.setLineWidth(0.2);
          for (var gl = 0; gl <= 4; gl++) doc.line(L, top + (ch * gl) / 4, R, top + (ch * gl) / 4);
          var slot = W / b.data.length, barW = Math.min(16, slot * 0.55);
          b.data.forEach(function (d, i) {
            var h = (d.value / max) * (ch - 6), bx = L + i * slot + (slot - barW) / 2;
            doc.setFillColor(RED[0], RED[1], RED[2]); doc.rect(bx, base - h, barW, h, 'F');
            doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(INK[0], INK[1], INK[2]);
            doc.text(String(d.value) + (b.unit || ''), bx + barW / 2, base - h - 1.5, { align: 'center' });
            doc.setFont('helvetica', 'normal'); doc.setTextColor(GRAY[0], GRAY[1], GRAY[2]);
            doc.text(doc.splitTextToSize(d.label, slot - 2).slice(0, 2), bx + barW / 2, base + 4.5, { align: 'center' });
          });
          y = base + 14;
        } else if (b.type === 'table') {
          ensure(24);
          doc.setFont('helvetica', 'bold'); doc.setFontSize(10.5); doc.setTextColor(INK[0], INK[1], INK[2]);
          doc.text(b.heading, L, y);
          doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(GRAY[0], GRAY[1], GRAY[2]);
          doc.text(b.rows.length + (b.rows.length === 1 ? ' record' : ' records'), R, y, { align: 'right' });
          y += 3;
          var body = b.rows.length ? b.rows.map(function (r) { return r.map(function (c) { return c == null ? '' : String(c); }); })
                                   : [[{ content: b.empty || 'No records match the selected filters.', colSpan: b.columns.length, styles: { halign: 'center', textColor: GRAY, fontStyle: 'italic' } }]];
          doc.autoTable({
            startY: y, head: [b.columns], body: body, theme: 'grid',
            margin: { left: L, right: 210 - R, top: 22, bottom: 20 },
            styles: { font: 'helvetica', fontSize: 8, cellPadding: 2.2, lineColor: LINE, lineWidth: 0.15, textColor: INK, overflow: 'linebreak' },
            headStyles: { fillColor: RED, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.8 },
            alternateRowStyles: { fillColor: [250, 250, 251] }
          });
          y = doc.lastAutoTable.finalY + 4;
          if (b.note) { doc.setFont('helvetica', 'italic'); doc.setFontSize(7.5); doc.setTextColor(GRAY[0], GRAY[1], GRAY[2]); var nl = doc.splitTextToSize(b.note, W); doc.text(nl, L, y + 2); y += nl.length * 3.5 + 2; }
          y += 6;
        }
      });
    });

    var total = doc.internal.getNumberOfPages();
    for (var p = 1; p <= total; p++) {
      doc.setPage(p);
      if (p > 1) drawHeader(doc, false);
      doc.setDrawColor(LINE[0], LINE[1], LINE[2]); doc.setLineWidth(0.2); doc.line(L, 284, R, 284);
      doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.setTextColor(GRAY[0], GRAY[1], GRAY[2]);
      doc.text('SEBENARNYA.MY  ·  ' + spec.id + '  ·  Generated ' + spec.generatedOn + ' by ' + spec.generatedBy, L, 288.5);
      doc.text('CONFIDENTIAL — For official use only. Do not distribute outside authorised agencies.', L, 292);
      doc.setFont('helvetica', 'bold'); doc.text('Page ' + p + ' of ' + total, R, 288.5, { align: 'right' });
    }
    doc.setProperties({ title: spec.title, subject: spec.period, author: spec.generatedBy, creator: 'SEBENARNYA.MY' });
    return doc.output('blob');
  }

  function toPrintFallback(spec) {
    var esc = function (s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); };
    var h = '<html><head><title>' + esc(spec.title) + '</title><style>@page{size:A4;margin:14mm}body{font:10pt Helvetica,Arial,sans-serif;color:#1A1A1A}h1{font-size:18pt;margin:0 0 4px}h2{font-size:13pt;margin:18px 0 8px;border-bottom:2px solid #C41230;padding-bottom:4px}h3{font-size:10.5pt;margin:14px 0 6px}.band{background:#C41230;color:#fff;padding:10px 14px;font-weight:bold;-webkit-print-color-adjust:exact;print-color-adjust:exact}table{width:100%;border-collapse:collapse;font-size:8.5pt}th{background:#C41230;color:#fff;text-align:left;padding:5px;-webkit-print-color-adjust:exact;print-color-adjust:exact}td{border:1px solid #E4E5E8;padding:5px}.meta td{border:none;padding:2px 8px 2px 0}.k{display:inline-block;border:1px solid #E4E5E8;padding:6px 10px;margin:0 6px 6px 0}.k b{display:block;font-size:13pt}</style></head><body>';
    h += '<div class="band" style="display:flex;align-items:center;gap:10px">' + LOGO_SVG.replace('width="512" height="512"', 'width="34" height="34"') + '<span>SEBENARNYA.MY — OFFICIAL REPORT</span></div><h1>' + esc(spec.title) + '</h1><div style="color:#8A8F98">' + esc(spec.subtitle || '') + '</div><table class="meta">';
    meta(spec).forEach(function (r) { h += '<tr><td><b>' + esc(r[0]) + '</b></td><td>' + esc(r[1]) + '</td></tr>'; });
    h += '</table>';
    spec.groups.forEach(function (g) {
      h += '<h2>' + esc(g.name) + '</h2>';
      (g.kpis || []).forEach(function (k) { h += '<span class="k">' + esc(k.label) + '<b>' + esc(k.value) + '</b></span>'; });
      g.blocks.forEach(function (b) {
        if (b.type !== 'table') return;
        h += '<h3>' + esc(b.heading) + '</h3><table><tr>' + b.columns.map(function (c) { return '<th>' + esc(c) + '</th>'; }).join('') + '</tr>';
        b.rows.forEach(function (r) { h += '<tr>' + r.map(function (c) { return '<td>' + esc(c) + '</td>'; }).join('') + '</tr>'; });
        h += '</table>';
      });
    });
    h += '<p style="color:#8A8F98;font-size:8pt;margin-top:20px">' + esc(spec.id) + ' · Generated ' + esc(spec.generatedOn) + ' by ' + esc(spec.generatedBy) + ' · CONFIDENTIAL</p></body></html>';
    var f = document.createElement('iframe');
    f.style.cssText = 'position:fixed;width:0;height:0;border:0;right:0;bottom:0';
    document.body.appendChild(f);
    f.contentDocument.open(); f.contentDocument.write(h); f.contentDocument.close();
    setTimeout(function () { f.contentWindow.focus(); f.contentWindow.print(); setTimeout(function () { f.remove(); }, 2000); }, 300);
  }

  /* ---------- Excel ---------- */
  function sheetName(name, used) {
    var base = String(name).replace(/[\\\/\?\*\[\]:]/g, '').slice(0, 28) || 'Sheet', n = base, i = 2;
    while (used[n]) n = base.slice(0, 26) + ' ' + i++;
    used[n] = 1; return n;
  }
  function summaryAoa(spec) {
    var a = [[spec.title], [spec.subtitle || ''], []];
    var bold = [0];
    meta(spec).forEach(function (r) { a.push(r); });
    spec.groups.forEach(function (g) {
      a.push([]); bold.push(a.length); a.push([g.name.toUpperCase()]);
      (g.kpis || []).forEach(function (k) { a.push([k.label, k.value]); });
    });
    a.push([]); a.push(['CONFIDENTIAL — For official use only.']);
    return { aoa: a, bold: bold };
  }
  function tableAoa(spec, t) {
    var a = [[t.block.heading], [t.group + '  ·  ' + spec.period], []];
    a.push(t.block.columns);
    t.block.rows.forEach(function (r) { a.push(r); });
    if (!t.block.rows.length) a.push([t.block.empty || 'No records match the selected filters.']);
    if (t.block.note) { a.push([]); a.push([t.block.note]); }
    return a;
  }
  function colWidths(aoa, from) {
    var w = [];
    aoa.slice(from).forEach(function (r) { r.forEach(function (c, i) { w[i] = Math.min(60, Math.max(w[i] || 10, String(c == null ? '' : c).length + 2)); }); });
    return w.map(function (x) { return { wch: x }; });
  }
  function toXlsx(spec) {
    var X = window.XLSX, wb = X.utils.book_new(), used = {};
    var sum = summaryAoa(spec), s = X.utils.aoa_to_sheet(sum.aoa);
    s['!cols'] = [{ wch: 34 }, { wch: 48 }];
    sum.bold.forEach(function (r) { var ref = X.utils.encode_cell({ r: r, c: 0 }); if (s[ref]) s[ref].s = { font: { bold: true } }; });
    if (s['A1']) s['A1'].s = { font: { bold: true, sz: 13 } };
    X.utils.book_append_sheet(wb, s, sheetName('Summary', used));
    tables(spec).forEach(function (t) {
      var aoa = tableAoa(spec, t), ws = X.utils.aoa_to_sheet(aoa);
      ws['!cols'] = colWidths(aoa, 3);
      ws['!autofilter'] = { ref: X.utils.encode_range({ s: { r: 3, c: 0 }, e: { r: 3 + Math.max(1, t.block.rows.length), c: t.block.columns.length - 1 } }) };
      X.utils.book_append_sheet(wb, ws, sheetName(t.block.sheet || t.block.heading, used));
    });
    wb.Props = { Title: spec.title, Author: spec.generatedBy, Company: spec.org, CreatedDate: new Date() };
    var out = X.write(wb, { bookType: 'xlsx', type: 'array' });
    return new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  }
  function toSpreadsheetML(spec) {
    var esc = function (s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); };
    var cell = function (v, st) { var num = typeof v === 'number'; return '<Cell' + (st ? ' ss:StyleID="' + st + '"' : '') + '><Data ss:Type="' + (num ? 'Number' : 'String') + '">' + esc(v) + '</Data></Cell>'; };
    var sheet = function (name, aoa, headRow) {
      return '<Worksheet ss:Name="' + esc(name) + '"><Table>' + aoa.map(function (r, i) {
        return '<Row>' + r.map(function (c) { return cell(c, i === 0 ? 't' : i === headRow ? 'h' : ''); }).join('') + '</Row>';
      }).join('') + '</Table></Worksheet>';
    };
    var used = {}, x = '<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">' +
      '<Styles><Style ss:ID="t"><Font ss:Bold="1" ss:Size="14"/></Style><Style ss:ID="h"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#C41230" ss:Pattern="Solid"/></Style></Styles>';
    x += sheet(sheetName('Summary', used), summaryAoa(spec).aoa, -1);
    tables(spec).forEach(function (t) { x += sheet(sheetName(t.block.sheet || t.block.heading, used), tableAoa(spec, t), 3); });
    x += '</Workbook>';
    return new Blob([x], { type: 'application/vnd.ms-excel' });
  }

  /* ---------- CSV ---------- */
  function toCsv(spec) {
    var q = function (v) { var s = String(v == null ? '' : v); return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; };
    var lines = [[spec.title]];
    meta(spec).forEach(function (r) { lines.push(r); });
    spec.groups.forEach(function (g) {
      lines.push([]); lines.push(['# ' + g.name]);
      (g.kpis || []).forEach(function (k) { lines.push([k.label, k.value]); });
      g.blocks.forEach(function (b) {
        if (b.type !== 'table') return;
        lines.push([]); lines.push(['## ' + b.heading]); lines.push(b.columns);
        b.rows.forEach(function (r) { lines.push(r); });
      });
    });
    return new Blob(['\ufeff' + lines.map(function (r) { return r.map(q).join(','); }).join('\r\n')], { type: 'text/csv;charset=utf-8' });
  }

  function run(spec, format) {
    var now = new Date();
    spec.id = spec.id || reportId(now);
    spec.generatedOn = spec.generatedOn || stamp(now);
    var ext = format === 'pdf' ? 'pdf' : format === 'csv' ? 'csv' : 'xlsx';
    var base = (spec.filename || 'SEBENARNYA-Report') + '_' + now.getFullYear() + pad(now.getMonth() + 1) + pad(now.getDate());
    var rowCount = tables(spec).reduce(function (a, t) { return a + t.block.rows.length; }, 0);
    var done = function (blob, name, note) { download(blob, name); return { filename: name, size: fmtSize(blob.size), id: spec.id, generatedOn: spec.generatedOn, rows: rowCount, note: note || '' }; };

    if (format === 'csv') return Promise.resolve(done(toCsv(spec), base + '.csv'));
    if (format === 'xlsx') {
      return load(LIBS.xlsx).then(function () { return done(toXlsx(spec), base + '.xlsx'); })
        .catch(function () { return done(toSpreadsheetML(spec), base + '.xls', 'Offline mode: saved as Excel 2003 XML (.xls).'); });
    }
    return load(LIBS.jspdf).then(function () { return load(LIBS.autotable); }).then(loadLogo)
      .then(function () { return done(toPdf(spec), base + '.pdf'); })
      .catch(function () { toPrintFallback(spec); return { filename: base + '.pdf', size: '—', id: spec.id, generatedOn: spec.generatedOn, rows: rowCount, note: 'PDF engine unavailable — opened print dialog. Choose “Save as PDF”.' }; });
  }

  /* ---------- Export dialog controller (shared by report screens) ----------
     cfg: { sections:[{key,label,desc}], buildSpec(opts) -> spec (groups carry .key), filename, defaultRange, onExported(res, fmt) } */
  var FORMATS = [
    { key: 'pdf', label: 'PDF', ext: 'PDF', icon: '#C41230', desc: 'Formatted official report with charts, ready to print or share.' },
    { key: 'xlsx', label: 'Excel', ext: 'XLSX', icon: '#1D7A3E', desc: 'Multi-sheet workbook with filterable tables for analysis.' },
    { key: 'csv', label: 'CSV', ext: 'CSV', icon: '#4B4F58', desc: 'Plain data file for import into other systems.' }
  ];
  function ymd() { var d = new Date(); return d.getFullYear() + pad(d.getMonth() + 1) + pad(d.getDate()); }
  function countOf(g) {
    var t = g.blocks.filter(function (b) { return b.type === 'table'; });
    return { tables: t.length, rows: t.reduce(function (a, b) { return a + b.rows.length; }, 0) };
  }
  function plural(n, w) { return n + ' ' + w + (n === 1 ? '' : 's'); }

  function vals(comp, cfg) {
    var e = Object.assign({ open: false, format: 'pdf', sel: {}, range: cfg.defaultRange || '6m', detail: true, charts: true, status: 'form', result: null, error: '' }, comp.state.exp || {});
    var set = function (p) { comp.setState(function (s) { return { exp: Object.assign({}, s.exp || {}, p) }; }); };
    comp._expHistory = comp._expHistory || [];
    var opts = function (sel) { return { sel: sel, range: e.range, detail: e.detail, charts: e.charts && e.format === 'pdf', format: e.format }; };
    var allSel = {}; cfg.sections.forEach(function (s) { allSel[s.key] = true; });
    var full = cfg.buildSpec(opts(allSel));
    var cur = cfg.buildSpec(opts(e.sel));
    var nSel = cfg.sections.filter(function (s) { return e.sel[s.key]; }).length;
    var curCount = cur.groups.reduce(function (a, g) { var c = countOf(g); return { tables: a.tables + c.tables, rows: a.rows + c.rows }; }, { tables: 0, rows: 0 });
    var ext = e.format === 'pdf' ? '.pdf' : e.format === 'csv' ? '.csv' : '.xlsx';
    var working = e.status === 'working';
    var res = e.result || {};

    var generate = function () {
      if (!nSel || working) return;
      var spec = cfg.buildSpec(opts(e.sel)), fmt = e.format, t0 = Date.now();
      set({ status: 'working', error: '' });
      run(spec, fmt).then(function (r) {
        setTimeout(function () {
          comp._lastSpec = spec; comp._lastFormat = fmt;
          r.contents = plural(spec.groups.length, 'report section') + ' · ' + plural(r.rows, 'row');
          comp._expHistory.unshift({ filename: r.filename, meta: r.size + ' · ' + r.generatedOn.split(', ')[1] });
          comp._expHistory = comp._expHistory.slice(0, 4);
          set({ status: 'done', result: r });
          if (cfg.onExported) cfg.onExported(r, fmt);
        }, Math.max(0, 650 - (Date.now() - t0)));
      }).catch(function (err) { set({ status: 'form', error: 'Export failed: ' + (err && err.message ? err.message : err) + '. Please try again.' }); });
    };

    return {
      openExport: function (format, sel) {
        var s0 = {}; (sel || cfg.sections.map(function (s) { return s.key; })).forEach(function (k) { s0[k] = true; });
        set({ open: true, format: format || 'pdf', sel: s0, range: cfg.defaultRange || e.range, status: 'form', error: '', result: null });
        window.SBExport.preload(format || 'pdf');
      },
      exportOpen: e.open,
      exportIntro: cfg.intro || 'Generate an official report file from the current data.',
      exportPreparedBy: cfg.preparedBy || '',
      exportShowRange: cfg.ranges !== false,
      exportRanges: cfg.ranges || [{ value: 'month', label: 'This Month (Sep 2026)' }, { value: '3m', label: 'Last 3 Months (Jul–Sep)' }, { value: '6m', label: 'Last 6 Months (Apr–Sep)' }, { value: 'year', label: 'This Year (2026)' }],
      exportIsForm: e.status !== 'done', exportIsDone: e.status === 'done', exportIsWorking: working,
      exportStopProp: function (ev) { ev.stopPropagation(); },
      onCloseExport: function () { if (!working) set({ open: false }); },
      exportFormats: FORMATS.map(function (f) {
        var on = e.format === f.key;
        return { label: f.label, ext: f.ext, desc: f.desc, iconBg: f.icon, border: on ? '#C41230' : '#E4E5E8', bg: on ? '#FDF3F4' : '#fff',
          radioBorder: on ? '#C41230' : '#C9CCD1', radioDot: on ? '#C41230' : 'transparent',
          onSelect: function () { set({ format: f.key }); window.SBExport.preload(f.key); } };
      }),
      exportSections: cfg.sections.map(function (s) {
        var on = !!e.sel[s.key], g = full.groups.filter(function (x) { return x.key === s.key; })[0], c = g ? countOf(g) : { tables: 0, rows: 0 };
        return { label: s.label, desc: s.desc, count: plural(c.tables, 'table') + ' · ' + plural(c.rows, 'row'),
          rowBorder: on ? '#F0C9D0' : '#EDEEF0', rowBg: on ? '#FDF7F8' : '#fff', boxBorder: on ? '#C41230' : '#C9CCD1', boxBg: on ? '#C41230' : '#fff',
          onToggle: function () { var n = Object.assign({}, e.sel); n[s.key] = !on; set({ sel: n }); } };
      }),
      toggleAllLabel: nSel === cfg.sections.length ? 'Clear all' : 'Select all',
      onToggleAllSections: function () { set({ sel: nSel === cfg.sections.length ? {} : allSel }); },
      exportRange: e.range, onExportRangeChange: function (ev) { set({ range: ev.target.value }); },
      exportToggles: [
        { label: cfg.detailLabel || 'Include detailed records', on: e.detail, enabled: true, onToggle: function () { set({ detail: !e.detail }); } },
        { label: e.format === 'pdf' ? 'Include charts' : 'Include charts (PDF only)', on: e.charts && e.format === 'pdf', enabled: e.format === 'pdf', onToggle: function () { if (e.format === 'pdf') set({ charts: !e.charts }); } }
      ].map(function (t) { return { label: t.label, onToggle: t.onToggle, trackBg: t.on ? '#C41230' : '#D4D6DA', knobLeft: t.on ? '16px' : '2px', opacity: t.enabled ? 1 : 0.5, cursor: t.enabled ? 'pointer' : 'not-allowed' }; }),
      exportFiltersText: [['Period', cur.period]].concat(cur.filters || []).map(function (f) { return f[0] + ': ' + f[1]; }).join('  ·  '),
      exportFilename: (cfg.filename || 'SEBENARNYA-Report') + '_' + ymd() + ext,
      exportSummaryText: nSel ? plural(nSel, 'report') + ' · ' + plural(curCount.tables, 'table') + ' · ' + plural(curCount.rows, 'row') : 'Select at least one report.',
      exportHasError: !!e.error, exportError: e.error,
      exportHasHistory: comp._expHistory.length > 0, exportHistory: comp._expHistory,
      exportBtnDisabled: !nSel || working, exportBtnBg: !nSel ? '#E3A3AE' : working ? '#A10E27' : '#C41230', exportBtnCursor: !nSel || working ? 'not-allowed' : 'pointer',
      exportBtnLabel: working ? 'Generating…' : 'Generate ' + (e.format === 'pdf' ? 'PDF' : e.format === 'csv' ? 'CSV' : 'Excel'),
      onGenerateExport: generate,
      exportResultFile: res.filename || '', exportResultId: res.id || '', exportResultContents: res.contents || '', exportResultTime: (res.generatedOn || '') + (res.size && res.size !== '—' ? '  ·  ' + res.size : ''),
      exportResultHasNote: !!res.note, exportResultNote: res.note || '',
      onExportAnother: function () { set({ status: 'form', result: null }); },
      onDownloadAgain: function () { if (comp._lastSpec) run(comp._lastSpec, comp._lastFormat); }
    };
  }

  window.SBExport = { run: run, vals: vals, preload: function (f) { if (f === 'pdf') load(LIBS.jspdf).then(function () { return load(LIBS.autotable); }).catch(function () {}); if (f === 'xlsx') load(LIBS.xlsx).catch(function () {}); } };
})();
